### ISSUE TITLE
Implement List styles

### ISSUE THREAD

**Issue by delta98** [delta98/ionic-material-design-lite#14]
Ensure list styles are inline with Material Design guidelines, including list separators/dividers

**Comment by Squix** [comment]
Could you please explain a little bit more how to make lists with ionic materail design lite ? Because I tried ion-list and this doesn't work, ther's no styling on my list :(

**Comment by delta98** [comment]
Can you provide your markup as you should use the standard Ionic markup

**Comment by Squix** [comment]
Here' is it : 

<ion-list>
        <ion-item collection-repeat="contact in contacts">
          {{contact.displayName}}
        </ion-item>
 </ion-list>

**Comment by Squix** [comment]
Yes here it is :
```html
<ion-list>
        <ion-item collection-repeat="contact in contacts">
          {{contact.displayName}}
        </ion-item>
</ion-list>
````

**Comment by Squix** [comment]
Might made a new issue ?

**Comment by delta98** [comment]
Does it style correctly when you don't use MDL library?

**Comment by Squix** [comment]
Yes, everything works fine when not using MDL library.
