### ISSUE TITLE
Error compiling sass

### ISSUE THREAD

**Issue by dciccale** [delta98/ionic-material-design-lite#32]
```sh
$ gulp sass
[22:47:01] Starting 'sass'...
{ [Error: bower_components/material-design-lite/src/_variables.scss
  311:20  ]
  message: 'bower_components/material-design-lite/src/_variables.scss\n  311:20  ',
  column: 20,
  line: 311,
  file: 'bower_components/material-design-lite/src/_variables.scss',
  status: 1,
  messageFormatted: '\u001b[4mbower_components/material-design-lite/src/_variables.scss\u001b[24m\n\u001b[90m  311:20\u001b[39m  ',
  name: 'Error',
  stack: 'Error: bower_components/material-design-lite/src/_variables.scss\n  311:20  \n    at options.error (/Users/Denis/git/ionic-material-design-lite/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:276:32)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-sass' }
```

It looks like an error in material-design-lite, it is not even clear what's going on. This is the raw output from sass.

however, i've run `sass bower_components/material-design-lite/src/material-design-lite.scss` and it works.

**Comment by delta98** [comment]
Have you followed the developer install steps? 

'npm install' and 'bower install' ?

What env are you building on?

**Comment by delta98** [comment]
@dciccale can you confirm whether the file `bower_components/material-design-lite/src/_variables.scss` exists in your bower directory, that looks like an issue with the material design lite dependency.

**Comment by dciccale** [comment]
i have all deps. i am just running `gulp sass` without any special env.

yeah, the file exists, and as i say, i can compile material-design-lite alone using `sass` bin directly like this from the root directory of this repo `sass bower_components/material-design-lite/src/material-design-lite.scss` and it compiles perfect.

something is wrong when doing it through `gulp sass`

i have sass 3.4.13.

have you tried compiling directly without gulp? `sass ./scss/**/*.scss` if it works well?

**Comment by dciccale** [comment]
i mean compiling  your files without gulp.

if i do it i get

```sh
$ sass ./scss/**/*.scss
Error: Undefined variable: "$bar-height".
        on line 4 of ./scss/bar/_bar.scss
  Use --trace for backtrace.
```

**Comment by dciccale** [comment]
if i compile only the `scss/ionic.material-design-lite.scss` file it works after fixing some things.

i think that the correct way should compile 1 entry point file like that one, right? not a glob pattern like scss/**/*.scss.

this works
```sh
sass scss/ionic.material-design-lite.scss
```

**Comment by delta98** [comment]
Yeah so you should compile the entry file `scss/ionic.material-design-lite.scss`. It's very strange as to why you are experiencing issues, let me look at my env and confirm a couple things and I will get back to you.

**Comment by delta98** [comment]
Ok, So my sass version is also `Sass 3.4.14`.

I think I've found the cause of the problem, there are import/extend errors due to a missing sass file not being imported. I'll issue a PR if you could try that and confirm it's resolved the issue for you.

The `sass` task in gulp is allowing it to fail silently.

**Comment by dciccale** [comment]
ok i wait for that PR to test it, thanks

**Comment by delta98** [comment]
Here is the PR #39 lets see if that resolves the issue. Try running the gulp task first. Then `sass scss/ionic.material-design-lite.scss`
