### ISSUE TITLE
Issue with google fonts

### ISSUE THREAD

**Issue by sriteja09** [delta98/ionic-material-design-lite#34]
Hi,
I am trying to include google fonts in the material design . Unable to apply font to the text . Please suggest me.

**Comment by delta98** [comment]
Take a look at any of the demos, currently they have to manually include the fonts. Add the following to your `<head>`.

`    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">`

I will be compiling the fonts directly into the project as part of #13 but can you let me know if the above solves your problem?

**Comment by delta98** [comment]
Closing as #41 resolves the requirement for externally loading Google font for Roboto

**Comment by sriteja09** [comment]
I want to include my fonts

**Comment by delta98** [comment]
Are you trying to override any of the existing font styles? If so that goes against Material Design and the purpose of the project.
