### ISSUE TITLE
bower ENOTFOUND     Package ionic-material-design-lite not found

### ISSUE THREAD

**Issue by jose909** [delta98/ionic-material-design-lite#43]
C:\Users\carlos\Desktop\trabajo_ionic\ionic-material-design>bower install ionic-ma
terial-design-lite
bower cached        git://github.com/driftyco/ionic-bower.git#1.0.1
bower validate      1.0.1 against git://github.com/driftyco/ionic-bower.git#1.0.
1
bower ENOTFOUND     Package ionic-material-design-lite not found

**Comment by delta98** [comment]
Hi @jose909 thanks for checking out the project. I won't be releasing to bower until 31st Aug when RC-1 is released. Until then it's still in heavy development. There's a note to this effect on the installation instructions. 

You can still clone the project and take a look at the demos until then.
