### ISSUE TITLE
Replace ":active" to ".activated"

### ISSUE THREAD

**Issue by rafael-franca** [delta98/ionic-material-design-lite#45]
When use ":active", some effects disappear in Chrome Desktop, like a "box-shadow".

**Comment by delta98** [comment]
Thanks @rafael-franca, can you provide further information on which elements and effects? ':active' is still required as '.activated' is applied by 'ui-sref' which may not always be applied.

**Comment by delta98** [comment]
Closing as the symptoms cannot be replicated and @rafael-franca has not responded.
