### ISSUE TITLE
How to change/set colors ?

### ISSUE THREAD

**Issue by dot-louis** [delta98/ionic-material-design-lite#52]
With sass you can define variable such as `$positive: #FF0000` to overwrite the default ionic colors.
However it seems you are hardcoding the material color palette in the module.

**Comment by delta98** [comment]
The colours have not been hard coded, they have been overridden here `https://github.com/delta98/ionic-material-design-lite/blob/master/scss/_variables.scss`.

This is exactly the same as how you would do it using Ionic's guide http://learn.ionicframework.com/videos/sass/

You can override the colours yourself by updating the variables in your `.scss` file.

**Comment by dot-louis** [comment]
Thanks for your quick answer! I'll try, and keep this issue updated
