### ISSUE TITLE
Android build fails after adding using Bower

### ISSUE THREAD

**Issue by dazziola** [delta98/ionic-material-design-lite#53]
I get a:
> Unable to open '/Users/darraghflynn/Desktop/testApp/platforms/android/build/outputs/apk/android-debug-unaligned.apk' as zip archive

error when I execute:

    ionic build android

The Android build works fine before adding the library and its dependencies using Bower.

Full stack trace:

> :zipalignDebugUnable to open '/Users/darraghflynn/Desktop/testApp/platforms/android/build/outputs/apk/android-debug-unaligned.apk' as zip archive
 FAILED

**Comment by delta98** [comment]
@dazziola if you remove the package from bower and re-run the build does it still gave you the same error? 

I'm not too sure as to why the build would fail as its a CSS and JS file that gets included. I'll take a look and see if I can replicate the issue.

If you have any further information that might be relevant that would be appreciated.

**Comment by delta98** [comment]
Closing due to no response.
