### ISSUE TITLE
Why we need .platform-android & .platform-override class on css

### ISSUE THREAD

**Issue by jazarja** [delta98/ionic-material-design-lite#57]
Why we need to have .platform-android & .platform-override class? I thought the primary reason we use ionic to make our life easier by make the design once and can work on all devices but those classes made me to spend more time debugging what makes differences between desktop & android.

Desktop:
![desktop](https://cloud.githubusercontent.com/assets/1103551/9426748/cfac32b6-497e-11e5-8676-ea714f070157.png)

Android:
![android](https://cloud.githubusercontent.com/assets/1103551/9426751/d55b6b1e-497e-11e5-873c-e031fb5cdc7b.png)

**Comment by delta98** [comment]
I'm not quite sure I understand your question? You don't need to handle those classes as they are added automatically for you.

.platform-override should only be added if you want iOS and Android to use Material Design. 

What was the problem you were trying to debug? If it's toggles, they have not yet been completed. Please look at the issues for features and their status.

You should never have to add platform classes yourself.
