### ISSUE TITLE
Getting started documentation

### ISSUE THREAD

**Issue by robertrafferty** [delta98/ionic-material-design-lite#61]
Should we start an ionic project an ionic app from the CLI and than bower install ionic-material-design-lite?

Thanks
Robert Rafferty

**Comment by delta98** [comment]
Hi @robertrafferty that would be my recommendation. Whilst it's still in development you might also need to include additional scripts until this is provided as a bundle, something I'm working on at the moment. 

Please check the installation steps on the read me particularly the notice about pre-release. 

Thanks
