### ISSUE TITLE
Ion-view style

### ISSUE THREAD

**Issue by acamenhas** [delta98/ionic-material-design-lite#64]
I'm trying style my "ion-view" with no success.
For that, i've compile a very simple example to explain better this issue.

P.S. Forgot to mension how can i costumize the header in a ion-view.

![index](https://cloud.githubusercontent.com/assets/14015712/9546533/5621288c-4d8b-11e5-92c4-2f2b36c78066.png)
![app](https://cloud.githubusercontent.com/assets/14015712/9546535/5c49a1ee-4d8b-11e5-8bcc-7bec0b90b9cc.png)
![intro](https://cloud.githubusercontent.com/assets/14015712/9546542/641b0dea-4d8b-11e5-87f5-c1a237dc97b5.png)
![result](https://cloud.githubusercontent.com/assets/14015712/9546546/69eaf6d6-4d8b-11e5-8e64-702f4282259d.png)

**Comment by delta98** [comment]
Could you create a code pen? Also you don't need to add any platform classes.

In terms of customising the header, in what way? You can use any of the ionic colour classes.

**Comment by acamenhas** [comment]
Each html (partial) file represent a page (ion-view). One view i would like to be with an extender header, other a normal header...
Yes i can create a code pen, no problem.

**Comment by acamenhas** [comment]
I've created a live demo to see this issue:

http://plnkr.co/edit/PayRrwmTvZFEdUswWijm?p=preview

**Comment by delta98** [comment]
It looks like you aren't including the css file correctly. Has it been installed properly?

**Comment by acamenhas** [comment]
I think so, but i can double check it.
Do you saw something wrong on the plnkr project?

**Comment by delta98** [comment]
You're using a beta version of Ionic and the MDL CSS isn't being included correctly.

**Comment by acamenhas** [comment]
Ok i made the alterations that you suggest but it remains the same:
http://plnkr.co/edit/PayRrwmTvZFEdUswWijm?p=preview

Something related to the ui-router?

**Comment by adyba** [comment]
Well I believe there are two issues. Your Plunk complains about `Angular not defined` coz you are not loading the modules in a right order. Your `index.html` line 12 should go between lines 15 and 16 (after ionic.bundle that introduce Angular to the browser). That was the easy part. 
The hard part is that even after resolving all the issues from the console, the app doesn't match the codepen Demo. Possible connected to #70

**Comment by delta98** [comment]
I will update shortly with a repo that uses an icon start app from the cli. This should provide a better comparison.

**Comment by delta98** [comment]
There is an issue with the tab underline styles which is being tracked here https://github.com/delta98/ionic-material-design-lite/issues/72
