### ISSUE TITLE
Menu button is not vertically centered

### ISSUE THREAD

**Issue by JobaDiniz** [delta98/ionic-material-design-lite#66]
![capture](https://cloud.githubusercontent.com/assets/165290/9567874/730f7d1e-4f10-11e5-9e3f-4092ebc1a851.PNG)

It seems the issue is `display: inherit;` from:
```
.bar .buttons-left span {
    margin-right: 5px;
    display: inherit;
```

If I remove `display: inherit;`, then the following rule will be applied:
```
.bar .buttons span {
    display: inline-block;
```

Which will fix the issue. But I'm not sure if it will break something else.

**Comment by delta98** [comment]
Could you provide the markup for the menu button, I'll take a look. If you'd like to create a PR for the `display:inline-block` change I can review it and merge it, if that resolves the issue.

**Comment by JobaDiniz** [comment]
```
<ion-nav-bar class="bar-balanced">
    <ion-nav-back-button class="button-icon ion-arrow-left-c"></ion-nav-back-button>

    <ion-nav-buttons side="left">
      <button class="button button-icon button-clear ion-navicon" ng-click="showMenu()">
      </button>
    </ion-nav-buttons>

    <ion-nav-title>
      <div class="bar item-input-inset">
        <label class="item-input-wrapper">
          <i class="icon ion-ios-search placeholder-icon"></i>
          <input type="search" ng-click="vm.goSearch()" placeholder="Search">
        </label>
      </div>
    </ion-nav-title>

    <ion-nav-buttons side="right">


      <a href="#/app/home/lightning" class="button button-icon button-clear ion-ios-calendar-outline">
      </a>
    </ion-nav-buttons>

  </ion-nav-bar>
```

It seems that the code is not from your lib, but from `ionic` itself, however it only takes place when I add ionic-material-design css.

I can fix this by overriding `.bar .buttons-left span` rule. Should I make a PR?

**Comment by delta98** [comment]
Yeah that would be awesome, I'll review it and hopefully merge it to resolve the issue.

Thanks
