### ISSUE TITLE
ionic run android command fails after install

### ISSUE THREAD

**Issue by FuzzyTree** [delta98/ionic-material-design-lite#73]
After running the `bower install ionic-material-design-lite`, the `ionic run android` command fails. I have verified this by creating several new projects and only being able to run the command successfully before installation.

<pre>
$ clear; ionic run android --stacktrace
Running command: ionic/returndb/hooks/after_prepare/010_add_platform_class.js ionic/returndb
Running command: ionic/returndb/platforms/android/cordova/run 
ANDROID_HOME=android_sdk
JAVA_HOME=jdk
WARNING : No target specified, deploying to device '02db59b408e4fad1'.
Running: ionic/returndb/platforms/android/gradlew cdvBuildDebug -b ionic/returndb/platforms/android/build.gradle -PcdvBuildArch=arm -Dorg.gradle.daemon=true
:preBuild
:compileDebugNdk UP-TO-DATE
:preDebugBuild
:checkDebugManifest
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles UP-TO-DATE
:CordovaLib:preBuild
:CordovaLib:preDebugBuild
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:processDebugResources UP-TO-DATE
:CordovaLib:generateDebugSources UP-TO-DATE
:CordovaLib:compileDebugJava UP-TO-DATE
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:packageDebugJar UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:packageDebugJniLibs UP-TO-DATE
:CordovaLib:packageDebugLocalJar UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:bundleDebug UP-TO-DATE
:prepareAndroidCordovaLibUnspecifiedDebugLibrary UP-TO-DATE
:prepareDebugDependencies
:compileDebugAidl UP-TO-DATE
:compileDebugRenderscript UP-TO-DATE
:generateDebugBuildConfig UP-TO-DATE
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets UP-TO-DATE
:generateDebugResValues UP-TO-DATE
:generateDebugResources UP-TO-DATE
:mergeDebugResources UP-TO-DATE
:processDebugManifest UP-TO-DATE
:processDebugResources UP-TO-DATE
:generateDebugSources UP-TO-DATE
:compileDebugJava UP-TO-DATE
:preDexDebug UP-TO-DATE
:dexDebug UP-TO-DATE
:processDebugJavaRes UP-TO-DATE
:validateDebugSigning
:packageDebug UP-TO-DATE
:zipalignDebugUnable to open 'ionic/returndb/platforms/android/build/outputs/apk/android-debug-unaligned.apk' as zip archive
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':zipalignDebug'.
> Process 'command 'android_sdk/build-tools/23.0.0/zipalign'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 24.307 secs

ionic/returndb/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: ionic/returndb/platforms/android/gradlew with args: cdvBuildDebug,-b,ionic/returndb/platforms/android/build.gradle,-PcdvBuildArch=arm,-Dorg.gradle.daemon=true
ERROR running one or more of the platforms: Error: ionic/returndb/platforms/android/cordova/run: Command failed with exit code 1
You may not have the required environment or OS to run this project
</pre>

My system info
<pre>
Cordova CLI: 5.2.0
Ionic Version: 1.1.0
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
OS: Distributor ID:     Ubuntu Description:     Ubuntu 15.04 
Node Version: v0.12.7
</pre>

**Comment by delta98** [comment]
Thanks for taking the time to create the issue and provide a lot of detail. Really sorry you've had no success whilst testing on several projects. 

It is a known issue, I'll update you shortly with a fix.

**Comment by delta98** [comment]
@FuzzyTree having researched a lot into this issue, it's caused by incorrect file paths. Can you take a look and see whether `platforms/android/build/outputs/apk/android-debug-unaligned.apk` actually exists within your project? 

I'm not able to replicate this issue locally.

**Comment by FuzzyTree** [comment]
Sorry for the late reply, I just had the chance to try it again with the latest RC1 and the issue has been fixed as I am able to run the kitchen sink on my phone now. In case you're wondering, the apk file did exist on the old version when the android build failed.

**Comment by FLGGithubDeveloper** [comment]
Hello @FuzzyTree 

What latest version you used to correct this? Ionic, cordova, node.js..?

**Comment by FuzzyTree** [comment]
@FLGGithubDeveloper 

It works for me using these

Ionic 1.1.1
Cordova 5.4.1
Node 0.12.7

And I'm using the JS/CSS from the nightly on rawgithub

**Comment by ahmedrshdy** [comment]
I am experiencing this issue, would you please let me know what the problem is about?

**Comment by degandhi024** [comment]
I received the same issue while building a small one screen project. So I figured to dig more and research the cause. This happens due to large libraries or bower components. I was using material design icons. the size of that component was more than 350MB. I removed all the additional files from the component and left it with SVGs and vola!

**Comment by ahayder** [comment]
My problem is exactly same as @degandhi024 "Material Design Icon" is the culprit.

**Comment by anneb** [comment]
same problem, cordova version 6.4.0. 
If the webapp contains node-modules (or bower-components) with material-design-icons, this is apparently too much for the compiler. Work-around: delete everything in node-modules/material-design-icons except node-modules/material-design-icons/iconfont

**Comment by lshekhar** [comment]
@anneb  You saved my day. It worked
