### ISSUE TITLE
Ionic 1.1.1 compatible?

### ISSUE THREAD

**Issue by trainerbill** [delta98/ionic-material-design-lite#84]
I am new to ionic but not angular.  Is this compatible with Ionic 1.1.1 start application?  I have spent hours trying to get this theme working.  I added the JS and CSS and added $ionicMaterialConfigProvider.enableForAllPlatforms().  There are no console errors but the theme is still the default from Ionic starter app.  Any suggestions?

**Comment by delta98** [comment]
It should be compatible, have you looked at whether the body has override class present?

**Comment by trainerbill** [comment]
@delta98 Yeah I am pretty sure, but there are a lot of different examples showing different ways of initializing:

```html
<body ng-app="starter" class="platform-android use-material-icons">
```

Does anyone have a tutorial of getting this to work from the last step of the ionic application starter build?

I have the .css and .js files but do not see the material design.

**Comment by delta98** [comment]
Take a look at https://github.com/IonicMaterialDesign/ionic-material-starter
