### ISSUE TITLE
Ping: Is development in progress

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [delta98/ionic-material-design-lite#85]
Great work, wanted to check do you have plan to maintain this repository or recommend alternative one? wanted to use in my project.

**Comment by delta98** [comment]
Hi, currently working across the new ionic 2 project and their implementation of Material Design. Do you have a particular issues you need resolving?

**Comment by gopalakrishnan-subramani** [comment]
@delta98, Wanted to use in my project  I started 3 weeks back, since the repository was not updated for few months, had question. Thanks. I shall use material design in my project.
